### ISSUE TITLE
UBIO username

### ISSUE THREAD

**Issue by csubio** [eandresleon/bitstarter#1]
Good morning, I'm Cassiano, from UBIO. We are a small web automation company from the UK.  Seeing you are no longer using the ubio github account, would you be able to please transfer it to us as we'd greatly benefit from it when releasing code to our customers? Please reach out to me at cs@ub.io to discuss.
Many thanks!
Cass

**Comment by csubio** [comment]
Hiya, any chance of getting back to me on this? Many thanks

**Comment by ubio** [comment]
Sorry. 
I forgot to reply (I’m on a paternity leave). 

I will transfer the ubio account as soon as posible. 
Please email anytime to remember It

E

**Comment by csubio** [comment]
Hi there, huge congrats on becoming a dad! I have two of my own, so I wish you loads of energy and patience. :) I'll make a note to drop you a line early January to remind you to transfer it. I appreciate your willingness to do so!
Many thanks!
Cass

**Comment by csubio** [comment]
Hello and happy new year. Just pinging you again to remind you about the transfer.
Thanks
Cass

**Comment by csubio** [comment]
Hello, just following up on this. Are you in a position to transfer the account yet? Many thanks!

**Comment by ubio** [comment]
Sorry again Casiano,
What do you need for me to transfer the GitHub 
?
E

**Comment by csubio** [comment]
Hi there, I'd imagine you'd create another user or organisation, get your repos transferred (I could do that if you'd like to save the hassle) then transfer the UBIO organisation/user over by either assigning to my csubio user or providing the login details. If you prefer I give you a ring or use gchat, please e-mail me your contact details at cs@ub.io and let's talk! Many many thanks!

**Comment by csubio** [comment]
Good morning, E. Just bumping this item up your diary. Is it still possible to transfer ownership? I can help transferring things, to make it easier. Just send me an e-mail and we can agree on how to move forward. Thanks!

**Comment by csubio** [comment]
Hello again, sorry to be a pain, but we'd really benefit from having the UBIO GitHub account. Would you mind doing the transfer? I can take care of moving it to another account for you, to avoid all the labour involved in that. Please send me an e-mail to cs@ub.io to make arrangements and I'd be extremely glad to help you.

**Comment by csubio** [comment]
I will also reach out to GitHub support to see whether they can help us make the move easier.

**Comment by ubio** [comment]
Hi Cassiano,
Before giving yoy the whole access I've tried to transfers all repos to a
new one account, but for whatever reason I've got errors (see the attached
pictures). I'll contact github to help me



[image: image.png]

**Comment by csubio** [comment]
Many thanks for this. Closing the issue.
